# Generated by Django 3.2 on 2022-08-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220827_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.FloatField()),
                ('fee_percentage', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.FloatField()),
                ('date_transaction', models.CharField(max_length=255)),
                ('base_currency', models.FloatField()),
                ('quote_currency', models.FloatField()),
            ],
        ),
    ]
